/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'trend' : IDL.Null,
  'intermediate' : IDL.Null,
  'basic' : IDL.Null,
});
export const Haircut = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'priceUSD' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getBCVRate' : IDL.Func([], [IDL.Float64], ['query']),
  'getHaircutPriceInVES' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Float64)],
      ['query'],
    ),
  'getHaircutsArray' : IDL.Func([], [IDL.Vec(Haircut)], ['query']),
  'getHaircutsByPrice' : IDL.Func([], [IDL.Vec(Haircut)], ['query']),
  'updateBCVRate' : IDL.Func([IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'trend' : IDL.Null,
    'intermediate' : IDL.Null,
    'basic' : IDL.Null,
  });
  const Haircut = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'priceUSD' : IDL.Float64,
  });
  
  return IDL.Service({
    'getBCVRate' : IDL.Func([], [IDL.Float64], ['query']),
    'getHaircutPriceInVES' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Float64)],
        ['query'],
      ),
    'getHaircutsArray' : IDL.Func([], [IDL.Vec(Haircut)], ['query']),
    'getHaircutsByPrice' : IDL.Func([], [IDL.Vec(Haircut)], ['query']),
    'updateBCVRate' : IDL.Func([IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };